### ISSUE TITLE
Conda Channel package

### ISSUE THREAD

**Issue by mert-kurttutan** [kadirnar/torchyolo#65]
Hi Kadir,

I think providing supporting installation through conda channels would be beneficial as conda-forge channel is somewhat popular for package management.

If this seems like a good idea to you, I can help with this on how to integrate `torchyolo` into `conda-forge` channel.

Also, managing python only packages is pretty automated when it comes to conda-forge channel

**Comment by kadirnar** [comment]
Hi @mert-kurttutan ,

Thank you for your interest. I don't know how to create a conda package. If you want to add it, I can accept it.
